feat: add 'users/{userId}/groups/represented'
vrchatapi/specification pull request #262
Opened 2023-10-15 00:46 UTC by KaydaFox

I believe I added everything needed, however this is my first time doing things with the OpenAPI spec

This endpoint can return either an empty object or an object containing some info about the group that's being represented

2023-10-15 01:09 UTC, ariesclark requested changes

2023-10-15 01:09 UTC, ariesclark commented on openapi/components/paths/users.yaml
> +                items:
Items is not a valid object property.
https://swagger.io/docs/specification/data-models/data-types/#object

2023-10-15 21:05 UTC, KaydaFox commented
uh- why did my last commit get added here wtf git lmao

2023-10-16 04:36 UTC, ariesclark commented
> uh- why did my last commit get added here wtf git lmao

Same tree as the one you made a pr for, so you'd be able to update an existing PR without having to close and reopen a new one.

2024-02-24 14:55 UTC, ariesclark approved these changes

2024-02-24 14:55 UTC, merged